### ISSUE TITLE
GPRparser is undefined

### ISSUE THREAD

**Issue by FanJingithub** [kemplab/FBA-pipeline#2]
Hello, when I run the code"parsedGPR = GPRparser(model)" in  "FBA-pipeline\Code + Models\data\vmax\vmax.ipynb",the system indicated that "GPRparser is undefined". I could not find the function named "GPRparser". How to solve this problem? Or could you provide code of this function?

**Comment by josh-lewis** [comment]
GPRparser is a function available from the COBRA toolbox: https://opencobra.github.io/cobratoolbox/stable/modules/dataIntegration/transcriptomics/preprocessing/index.html
